### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by maint623** [PikaMug/LocaleLib#25]
I added it to my gradle build.
I'm trying to use it as 
` private final LocaleManager localeManager = new LocaleManager(); `
but I get a NoClassDefFoundError error

**Comment by PikaMug** [comment]
Kindly provide the full error.

**Comment by maint623** [comment]
java.lang.NoClassDefFoundError: me/pikamug/localelib/LocaleManager
        at kr.maint.customshop.ShopEvent.<init>(ShopEvent.java:23) ~[CustomShop-1.0-SNAPSHOT.jar:?]
        at kr.maint.customshop.CustomShop.onEnable(CustomShop.java:29) ~[CustomShop-1.0-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.19.3.jar:git-Paper-406]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.3.jar:git-Paper-406]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:561) ~[paper-1.19.3.jar:git-Paper-406]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:472) ~[paper-1.19.3.jar:git-Paper-406]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.reload(CraftServer.java:1020) ~[paper-1.19.3.jar:git-Paper-406]
        at org.bukkit.Bukkit.reload(Bukkit.java:930) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:912) ~[paper-1.19.3.jar:git-Paper-406]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchServerCommand(CraftServer.java:875) ~[paper-1.19.3.jar:git-Paper-406]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:501) ~[paper-1.19.3.jar:git-Paper-406]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:448) ~[paper-1.19.3.jar:git-Paper-406]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-406]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-406]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-406]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.pikamug.localelib.LocaleManager
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:199) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:146) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 20 more

**Comment by PikaMug** [comment]
It seems as though LocaleLib hasn't been shaded into your plugin jar.

**Comment by maint623** [comment]
How do I do this

**Comment by PikaMug** [comment]
https://www.spigotmc.org/threads/how-to-shade-apis-with-gradle.416273/
